/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.awt.Color;
import view.DataGuru;
import view.DataKelas;
import view.DataPresensi;
import view.DataPresensi2;
import view.DataSiswa;
import view.DataTransaksi;


/**
 *
 * @author aliazwar
 */
public class MenuUtama extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        NameYayasan1 = new javax.swing.JLabel();
        LogoYayasan = new javax.swing.JLabel();
        NameMasterData = new javax.swing.JLabel();
        pn_DataSiswa = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_DataSiswa = new javax.swing.JLabel();
        pn_DataKelas = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_DataKelas = new javax.swing.JLabel();
        pn_DataGuru = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_DataGuru = new javax.swing.JLabel();
        pn_DataPresensi = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_Presensi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pn_Presensi = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_DataSiswa5 = new javax.swing.JLabel();
        pn_DataTransaksi = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_DataSiswa6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pn_CetakLaporan = new javax.swing.JPanel();
        pn_line6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_DataSiswa7 = new javax.swing.JLabel();
        NameYayasan2 = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_navbar = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 768));

        NameYayasan1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NameYayasan1.setText("Yayasan Pendidikan");

        LogoYayasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Badlion-60.png"))); // NOI18N

        NameMasterData.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        NameMasterData.setForeground(new java.awt.Color(102, 102, 102));
        NameMasterData.setText("Data Sekolah");

        pn_DataSiswa.setBackground(new java.awt.Color(255, 255, 255));

        pn_line.setBackground(new java.awt.Color(255, 255, 255));
        pn_line.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Children-50.png"))); // NOI18N

        btn_DataSiswa.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btn_DataSiswa.setForeground(new java.awt.Color(51, 51, 51));
        btn_DataSiswa.setText("Data Siswa/i");
        btn_DataSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataSiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DataSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DataSiswaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_DataSiswaLayout = new javax.swing.GroupLayout(pn_DataSiswa);
        pn_DataSiswa.setLayout(pn_DataSiswaLayout);
        pn_DataSiswaLayout.setHorizontalGroup(
            pn_DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DataSiswaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_DataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataSiswaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pn_DataSiswaLayout.setVerticalGroup(
            pn_DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_DataSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DataSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_DataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataSiswaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_DataKelas.setBackground(new java.awt.Color(255, 255, 255));

        pn_line1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Class-50.png"))); // NOI18N

        btn_DataKelas.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btn_DataKelas.setForeground(new java.awt.Color(51, 51, 51));
        btn_DataKelas.setText("Data Kelas");
        btn_DataKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DataKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DataKelasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_DataKelasLayout = new javax.swing.GroupLayout(pn_DataKelas);
        pn_DataKelas.setLayout(pn_DataKelasLayout);
        pn_DataKelasLayout.setHorizontalGroup(
            pn_DataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DataKelasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_DataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_DataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataKelasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pn_DataKelasLayout.setVerticalGroup(
            pn_DataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_DataKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DataKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_DataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataKelasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_DataGuru.setBackground(new java.awt.Color(255, 255, 255));

        pn_line2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Teacher-50.png"))); // NOI18N

        btn_DataGuru.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btn_DataGuru.setForeground(new java.awt.Color(51, 51, 51));
        btn_DataGuru.setText("Data Guru");
        btn_DataGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataGuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DataGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DataGuruMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_DataGuruLayout = new javax.swing.GroupLayout(pn_DataGuru);
        pn_DataGuru.setLayout(pn_DataGuruLayout);
        pn_DataGuruLayout.setHorizontalGroup(
            pn_DataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DataGuruLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_DataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_DataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataGuruLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pn_DataGuruLayout.setVerticalGroup(
            pn_DataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_DataGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DataGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_DataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataGuruLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_DataPresensi.setBackground(new java.awt.Color(255, 255, 255));

        pn_line3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Report Card-50.png"))); // NOI18N

        btn_Presensi.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btn_Presensi.setForeground(new java.awt.Color(51, 51, 51));
        btn_Presensi.setText("Presensi Siswa/i");
        btn_Presensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PresensiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PresensiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PresensiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_DataPresensiLayout = new javax.swing.GroupLayout(pn_DataPresensi);
        pn_DataPresensi.setLayout(pn_DataPresensiLayout);
        pn_DataPresensiLayout.setHorizontalGroup(
            pn_DataPresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DataPresensiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_Presensi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pn_DataPresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataPresensiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pn_DataPresensiLayout.setVerticalGroup(
            pn_DataPresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_DataPresensiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Presensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_DataPresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataPresensiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        jLabel6.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Data Laporan");

        pn_Presensi.setBackground(new java.awt.Color(255, 255, 255));

        pn_line4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Bar Chart-50.png"))); // NOI18N

        btn_DataSiswa5.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btn_DataSiswa5.setText("Data Presensi");
        btn_DataSiswa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataSiswa5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DataSiswa5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DataSiswa5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_PresensiLayout = new javax.swing.GroupLayout(pn_Presensi);
        pn_Presensi.setLayout(pn_PresensiLayout);
        pn_PresensiLayout.setHorizontalGroup(
            pn_PresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_PresensiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_DataSiswa5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_PresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_PresensiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pn_PresensiLayout.setVerticalGroup(
            pn_PresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_PresensiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DataSiswa5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_PresensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_PresensiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_DataTransaksi.setBackground(new java.awt.Color(255, 255, 255));

        pn_line5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Receipt Dollar-50.png"))); // NOI18N

        btn_DataSiswa6.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btn_DataSiswa6.setText("Data Transaksi");
        btn_DataSiswa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataSiswa6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DataSiswa6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DataSiswa6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_DataTransaksiLayout = new javax.swing.GroupLayout(pn_DataTransaksi);
        pn_DataTransaksi.setLayout(pn_DataTransaksiLayout);
        pn_DataTransaksiLayout.setHorizontalGroup(
            pn_DataTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DataTransaksiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_DataSiswa6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_DataTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataTransaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pn_DataTransaksiLayout.setVerticalGroup(
            pn_DataTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_DataTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DataSiswa6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_DataTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DataTransaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel7.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Cetak Data Laporan");

        pn_CetakLaporan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line6Layout = new javax.swing.GroupLayout(pn_line6);
        pn_line6.setLayout(pn_line6Layout);
        pn_line6Layout.setHorizontalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pn_line6Layout.setVerticalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/icons8-Print-50.png"))); // NOI18N

        btn_DataSiswa7.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btn_DataSiswa7.setText("Cetak Laporan");
        btn_DataSiswa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataSiswa7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DataSiswa7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DataSiswa7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_CetakLaporanLayout = new javax.swing.GroupLayout(pn_CetakLaporan);
        pn_CetakLaporan.setLayout(pn_CetakLaporanLayout);
        pn_CetakLaporanLayout.setHorizontalGroup(
            pn_CetakLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CetakLaporanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_DataSiswa7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(pn_CetakLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_CetakLaporanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pn_CetakLaporanLayout.setVerticalGroup(
            pn_CetakLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_CetakLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_CetakLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_DataSiswa7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_CetakLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_CetakLaporanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        NameYayasan2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NameYayasan2.setText("Al-Mabuq");

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameMasterData)
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addComponent(LogoYayasan)
                                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_kiriLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(NameYayasan1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_kiriLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(NameYayasan2))))))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_DataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_DataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_DataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_DataPresensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_Presensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_DataTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_CetakLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoYayasan)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(NameYayasan1)
                        .addGap(10, 10, 10)
                        .addComponent(NameYayasan2)))
                .addGap(30, 30, 30)
                .addComponent(NameMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pn_DataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pn_DataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pn_DataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pn_DataPresensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pn_Presensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pn_DataTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pn_CetakLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_navbar.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(0, 102, 102));
        pn_dasar.setLayout(new java.awt.BorderLayout());

        pn_utama.setBackground(new java.awt.Color(0, 102, 102));
        pn_utama.setPreferredSize(new java.awt.Dimension(1037, 749));
        pn_utama.setRequestFocusEnabled(false);
        pn_utama.setLayout(new java.awt.BorderLayout());
        pn_dasar.add(pn_utama, java.awt.BorderLayout.PAGE_START);

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
            
     int xx, xy;
    private void btn_DataSiswa7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa7MouseExited
        pn_CetakLaporan.setBackground(new Color(255,255,255));
        pn_line6.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_DataSiswa7MouseExited

    private void btn_DataSiswa7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa7MouseEntered
        pn_CetakLaporan.setBackground(new Color(250,250,250));
        pn_line6.setBackground(new Color(65,105,225));
    }//GEN-LAST:event_btn_DataSiswa7MouseEntered

    private void btn_DataSiswa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa7MouseClicked
        pn_CetakLaporan.setBackground(new Color(240,240,240));
        pn_line6.setBackground(new Color(65,105,225));

        pn_utama.removeAll();
        pn_utama.add(new DataPresensi());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_DataSiswa7MouseClicked

    private void btn_DataSiswa6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa6MouseExited
        pn_DataTransaksi.setBackground(new Color(255,255,255));
        pn_line5.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_DataSiswa6MouseExited

    private void btn_DataSiswa6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa6MouseEntered
        pn_DataTransaksi.setBackground(new Color(250,250,250));
        pn_line5.setBackground(new Color(65,105,225));
    }//GEN-LAST:event_btn_DataSiswa6MouseEntered

    private void btn_DataSiswa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa6MouseClicked
        pn_DataTransaksi.setBackground(new Color(240,240,240));
        pn_line5.setBackground(new Color(65,105,225));

        pn_utama.removeAll();
        pn_utama.add(new DataTransaksi());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_DataSiswa6MouseClicked

    private void btn_DataSiswa5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa5MouseExited
        pn_Presensi.setBackground(new Color(255,255,255));
        pn_line4.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_DataSiswa5MouseExited

    private void btn_DataSiswa5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa5MouseEntered
        pn_Presensi.setBackground(new Color(250,250,250));
        pn_line4.setBackground(new Color(65,105,225));
    }//GEN-LAST:event_btn_DataSiswa5MouseEntered

    private void btn_DataSiswa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswa5MouseClicked
        pn_Presensi.setBackground(new Color(240,240,240));
        pn_line4.setBackground(new Color(65,105,225));

        pn_utama.removeAll();
        pn_utama.add(new DataPresensi2());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_DataSiswa5MouseClicked

    private void btn_PresensiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PresensiMouseExited
        pn_DataPresensi.setBackground(new Color(255,255,255));
        pn_line3.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_PresensiMouseExited

    private void btn_PresensiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PresensiMouseEntered
        pn_DataPresensi.setBackground(new Color(250,250,250));
        pn_line3.setBackground(new Color(65,105,225));
    }//GEN-LAST:event_btn_PresensiMouseEntered

    private void btn_PresensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PresensiMouseClicked
        pn_DataPresensi.setBackground(new Color(240,240,240));
        pn_line3.setBackground(new Color(65,105,225));

        pn_utama.removeAll();
        pn_utama.add(new DataPresensi());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_PresensiMouseClicked

    private void btn_DataGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataGuruMouseExited
        pn_DataGuru.setBackground(new Color(255,255,255));
        pn_line2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_DataGuruMouseExited

    private void btn_DataGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataGuruMouseEntered
        pn_DataGuru.setBackground(new Color(250,250,250));
        pn_line2.setBackground(new Color(65,105,225));
    }//GEN-LAST:event_btn_DataGuruMouseEntered

    private void btn_DataGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataGuruMouseClicked
        pn_DataGuru.setBackground(new Color(240,240,240));
        pn_line2.setBackground(new Color(65,105,225));

        pn_utama.removeAll();
        pn_utama.add(new DataGuru());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_DataGuruMouseClicked

    private void btn_DataKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataKelasMouseExited
        pn_DataKelas.setBackground(new Color(255,255,255));
        pn_line1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_DataKelasMouseExited

    private void btn_DataKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataKelasMouseEntered
        pn_DataKelas.setBackground(new Color(250,250,250));
        pn_line1.setBackground(new Color(65,105,225));
    }//GEN-LAST:event_btn_DataKelasMouseEntered

    private void btn_DataKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataKelasMouseClicked
        pn_DataKelas.setBackground(new Color(240,240,240));
        pn_line1.setBackground(new Color(65,105,225));

        pn_utama.removeAll();
        pn_utama.add(new DataKelas());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_DataKelasMouseClicked

    private void btn_DataSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswaMouseExited
        pn_DataSiswa.setBackground(new Color(255,255,255));
        pn_line.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_DataSiswaMouseExited

    private void btn_DataSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswaMouseEntered
        pn_DataSiswa.setBackground(new Color(250,250,250));
        pn_line.setBackground(new Color(65,105,225));
    }//GEN-LAST:event_btn_DataSiswaMouseEntered

    private void btn_DataSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataSiswaMouseClicked
        pn_DataSiswa.setBackground(new Color(240,240,240));
        pn_line.setBackground(new Color(65,105,225));

        pn_utama.removeAll();
        pn_utama.add(new DataSiswa());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_DataSiswaMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    
    /**   Ω
     * @param args the command line arguments50
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoYayasan;
    private javax.swing.JLabel NameMasterData;
    private javax.swing.JLabel NameYayasan1;
    private javax.swing.JLabel NameYayasan2;
    private javax.swing.JLabel btn_DataGuru;
    private javax.swing.JLabel btn_DataKelas;
    private javax.swing.JLabel btn_DataSiswa;
    private javax.swing.JLabel btn_DataSiswa5;
    private javax.swing.JLabel btn_DataSiswa6;
    private javax.swing.JLabel btn_DataSiswa7;
    private javax.swing.JLabel btn_Presensi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pn_CetakLaporan;
    private javax.swing.JPanel pn_DataGuru;
    private javax.swing.JPanel pn_DataKelas;
    private javax.swing.JPanel pn_DataPresensi;
    private javax.swing.JPanel pn_DataSiswa;
    private javax.swing.JPanel pn_DataTransaksi;
    private javax.swing.JPanel pn_Presensi;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_line6;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
